# fly.toml app configuration file generated for beth-demo on 2023-07-19T14:24:30+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "beth-demo"
primary_region = "iad"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
